# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
